# Generated by Django 3.2.7 on 2021-09-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
