# Generated by Django 3.2.7 on 2021-09-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_post_comment_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='postsComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='postsLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='posts',
        ),
        migrations.DeleteModel(
            name='Post_comment',
        ),
        migrations.AddField(
            model_name='postslike',
            name='postLike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLike', to='post.posts'),
        ),
        migrations.AddField(
            model_name='postslike',
            name='user_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postscomment',
            name='postComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postComment', to='post.posts'),
        ),
        migrations.AddField(
            model_name='postscomment',
            name='user_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
